<?php
/**
 * @file
 * Code for the Cartaro Demo feature.
 */

include_once('cartaro_demo.features.inc');

/**
 * Implements hook_enable().
 */
function cartaro_demo_enable() {

  features_rebuild();
  drupal_flush_all_caches();

  cartaro_demo_save_node('Get started', 'Welcome to Cartaro!

This demo provides you with an exemplary configuration of the Cartaro distribution. More precisely it contains a content type to store the name and location of a capital city, a GeoServer layer and style to publish all capital cities and an OpenLayers map to render those cities on a map. On the front page you will find all components brought together.

Next steps:
- Create content types with PostGIS fields that suite your needs.
- Create GeoServer layers to publish content types with PostGIS fields.
- Create GeoServer styles to customize the rendering of GeoServer layers.
- Add GeoServer layers to your OpenLayers maps.

Detailed documentation: http://cartaro.org/documentation');

  $capitals = dirname(__FILE__) . DIRECTORY_SEPARATOR  . 'capitals.csv';
  if (($handle = fopen($capitals, 'r')) !== FALSE) {
    while (($data = fgetcsv($handle, 1000, ';')) !== FALSE) {
      cartaro_demo_save_node($data[0], $data[1], "POINT($data[3] $data[2])");
    }
    fclose($handle);
  }

  $blocks = array(
    array(
      'module' => 'block',
      'region' => 'footer',
      'body' => 'A Cartaro demo - www.cartaro.org',
      'info' => 'Cartaro footer',
      'format' => 'plain_text',
    ),
  );
  cartaro_demo_configure_blocks($blocks);

  // Create Demo user.
  if (FALSE == user_load_by_name('demo')) {
    user_save(NULL, array(
      'name' => 'demo',
      'pass' => 'demo',
      'init' => 'info@cartaro.org',
      'mail' => 'info@cartaro.org',
      'roles' =>  array('3' => 'demo'),
      'timezone' => 'Europe/Berlin',
      'status' => 1,
    ));
  }

  $theme_frontmap_settings = variable_get('theme_frontmap_settings', array());
  $theme_frontmap_settings['frontmap'] = 'frontmap';
  variable_set('theme_frontmap_settings', $theme_frontmap_settings);
}

function cartaro_demo_save_node($title, $body, $location = FALSE) {
  $node = new stdClass();
  $node->title = $title;
  $node->body['und'][0]['value'] = $body;
  $node->body['und'][0]['summary'] = $body;
  $node->body['und'][0]['format'] = 'plain_text';
  $node->uid = 1;
  $node->language = 'und';
  $node->status = 1;
  $node->promote = 1;

  if ($location) {
    $node->field_location['und'][0]['feeds'] = TRUE; // Disables reprojection.
    $node->field_location['und'][0]['wkt'] = $location;
    $node->type = 'capital';
  }
  else {
    $node->type = 'page';
  }

  node_save($node);
}

function cartaro_demo_configure_blocks($blocks) {
  foreach ($blocks as $block) {

    if ($block['module'] == 'block') {
      // Create and activate a custom block.
      db_merge('block_custom')
        ->key(array('info' => $block['info']))
        ->fields(array(
          'body' => $block['body'],
          'info' => $block['info'],
          'format' => $block['format'],
        ))
        ->execute();

      $block['delta'] = db_select('block_custom', 'bc')
        ->fields('bc', array('bid'))
        ->condition('info', 'Cartaro footer')
        ->execute()
        ->fetchField();

      db_merge('block')
        ->key(array(
          'module' => $block['module'],
          'delta' => $block['delta'],
          'theme' => 'frontmap',
        ))
        ->fields(array(
          'pages' => '',
          'status' => 1,
          'module' => $block['module'],
          'theme' => 'frontmap',
          'delta' => $block['delta'],
          'cache' => DRUPAL_NO_CACHE,
          'region' => $block['region'],
        ))
        ->execute();
    }
    else {
      // Activate a menu block.
      db_update('block')
        ->fields(array(
          'status' => 1,
          'region' => $block['region'],
        ))
        ->condition('theme', 'frontmap')
        ->condition('module', $block['module'])
        ->condition('delta', $block['delta'])
        ->execute();
    }
  }
}
